#!/usr/bin/env bash

###
# Helper functions
##
function info () {
	printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

function success() {
	printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

function warn() {
  printf "\r\033[2K  [\033[0;31mWARN\033[0m] %s\n" "$1"
}

function sub_warn() {
  printf "\r\033[2K  [\033[0;31mWARN\033[0m] \t%s\n" "$1"
}



# Makes sure that the script doesn't run on stuff outside of the committed repo
stash_push

if bin/build-dev-leave-prod true ; then
    cleanup $jekyll_pid true
else
    cleanup $jekyll_pid true
    exit 1
fi
