# General build settings
language: ruby
rvm:
  - 2.4.1
branches:
  only:
    - source
sudo: false

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Notification settings
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

# Dependency installation steps
install:
  - bundle install
  - npm install

# Build steps
script:
  # Generates the static site
  - bundle exec jekyll build

# Testing steps
after_script:
  # Runs an html output validator
  - htmlproofer --assume-extension ./_site

# Deployment steps (on success)
after_success:
  - cd _site
  - git init
  - git config user.name "Jason Yao"
  - git config user.email "JasonYao@nyu.edu"
  - git remote add upstream "https://$GITHUB_ACCESS_TOKEN@github.com/JasonYao/JasonYao.github.io.git"
  - git fetch upstream
  - git reset upstream/master
  - git add -A .
  - git commit -m "[Build] ${TRAVIS_COMMIT}"
  - git push -q upstream HEAD:master


