# General build settings
language: ruby
rvm:
  - 2.4.1
branches:
  only:
    - source
sudo: false

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Notification settings
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

# Dependency installation steps
install:
  - bundle install
  - npm install

# Build steps
script:
  # Generates the static site
  - bundle exec jekyll build

# Testing steps
after_script:
  # Runs through any validators and tests
  - ./bin/test

# Deployment steps (on success & on the correct branch)
after_success:
  - ./bin/deploy
