# General build settings
sudo: false
dist: trusty

language: ruby


cache:
  directories:
  - "$HOME/opt"

rvm:
  - 2.4.1
branches:
  only:
    - source

addons:
  apt:
    packages:
    # Required for html-proofer, more info here: https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332770021
    - libcurl4-openssl-dev
    # Required for converting to/from webp images
    - webp
    - libwebp-dev
    # Required for ImageMagick
    - libjpeg-dev
    - libpng-dev
    - libgif-dev
    - libmagickwand-dev

#env:
#  global:
#  - IMAGEMAGICK_VERSION: '6.9.9-26'
#  - LIBWEBP_VERSION: '0.6.1'

# Notification settings
# TODO look into fixing this
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

before_install:
  - which convert
  - convert --version
  - convert -list format
  - cd $TRAVIS_BUILD_DIR
  - convert assets/img/projects/0-hamilton.jpg assets/img/projects/0-hamilton-test.webp
#  - export PATH=$HOME/opt/bin:$PATH
#  # Checks if Imagemagick is already sufficient version
#  # If not installs it from the sources
#  - convert -version | grep $IMAGEMAGICK_VERSION || {
#      export CORES=$(nproc) &&
#      echo "Using $CORES cores for compiling..." &&
#      cd /tmp &&
#      curl -O https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-$LIBWEBP_VERSION.tar.gz &&
#      tar xvzf libwebp-$LIBWEBP_VERSION.tar.gz &&
#      cd libwebp-* &&
#      ./configure --prefix=$HOME/opt &&
#      make -j$CORES &&
#      make install -j$CORES &&
#      cd /tmp &&
#      curl -O https://www.imagemagick.org/download/ImageMagick-$IMAGEMAGICK_VERSION.tar.gz &&
#      tar xvzf ImageMagick-$IMAGEMAGICK_VERSION.tar.gz &&
#      cd ImageMagick-* &&
#      ./configure --prefix=$HOME/opt &&
#      make -j$CORES &&
#      make install -j$CORES &&
#      $HOME/opt/bin/magick -version | grep $IMAGEMAGICK_VERSION &&
#      cd $TRAVIS_BUILD_DIR; }
#
#  # Update library paths for programs
#  - export LD_FLAGS=-L$HOME/opt/lib
#  - export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$HOME/opt/lib
#  - export CPATH=$CPATH:$HOME/opt/include

#  - sudo apt-get build-dep imagemagick
#  - mkdir -p ~/image-magick
#  - wget https://github.com/ImageMagick/ImageMagick/archive/6.9.9-26.tar.gz -O ~/image-magick/image-magick.tar.gz
#  - tar xzvf ~/image-magick/image-magick.tar.gz -C ~/image-magick
#  - cd ~/image-magick/ImageMagick-6.9.9-26
#  - ./configure --with-webp
##  - sudo checkinstall
#  - sudo make
#  - sudo make install

# Dependency installation steps
install:
  - bundle install
  - npm install -g jsonlint  # Required global install otherwise it doesn't work
  - npm install

script:
  # Generates the static site and runs through the test suite
  - bin/build-dev-leave-prod false

# We only run the tests and deployment checks if the build succeeded
after_success:
  # Deployment steps (on success & on the correct branch)
  - bin/deploy
