# General build settings
sudo: false
dist: trusty

language: ruby

rvm:
  - 2.4.1
branches:
  only:
    - source

addons:
  apt:
    packages:
    # Required for html-proofer, more info here: https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332770021
    - libcurl4-openssl-dev
    # Required for converting to/from webp images
    - webp
    - libwebp-dev
    # Required for ImageMagick
    - build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev

# Notification settings
# TODO look into fixing this
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

before_install:
  - sudo apt-get build-dep imagemagick
  - wget https://github.com/ImageMagick/ImageMagick/archive/6.9.9-26.tar.gz -O image-magick.tar.gz
  - tar xzvf image-magick.tar.gz
  - cd image-magick
  - ./configure
  - sudo checkinstall

# Dependency installation steps
install:
  - bundle install
  - npm install -g jsonlint  # Required global install otherwise it doesn't work
  - npm install

script:
  # Generates the static site and runs through the test suite
  - bin/build-dev-leave-prod false

# We only run the tests and deployment checks if the build succeeded
after_success:
  # Deployment steps (on success & on the correct branch)
  - bin/deploy
