# General build settings
sudo: false
dist: trusty

language: ruby

rvm:
  - 2.4.1
branches:
  only:
    - source

addons:
  apt:
    packages:
    # Required for html-proofer, more info here: https://github.com/gjtorikian/html-proofer/issues/376#issuecomment-332770021
    - libcurl4-openssl-dev

# Notification settings
# TODO look into fixing this
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

# Dependency installation steps
before_install:
  - bundle install
  - npm install -g jsonlint  # Required global install otherwise it doesn't work
  - npm install

# Build steps
#install:

# Test steps
script:
  # Generates the static site and runs through the test suite
  - bin/build-dev-leave-prod false

#  # Runs through any validators and tests
#  - bin/test

# We only run the tests and deployment checks if the build succeeded
after_success:
  # Deployment steps (on success & on the correct branch)
  - bin/deploy
