# General build settings
language: ruby
rvm:
  - 2.4.1
branches:
  only:
    - source
sudo: false

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

# Notification settings
notifications:
  email:
    recipients:
      - hello@jasonyao.com
    # Only sends an email when the build status changes
    on_success: change

# Dependency installation steps
before_install:
  - bundle install
  - npm install

# Build steps
install:
  # Generates the static site
  - bundle exec jekyll build

# Test steps
script:
  # Runs through any validators and tests
  # - sudo apt-get update &> /dev/null
  # - sudo apt-get install curl
  - curl www.google.com
  - bin/test

# We only run the tests and deployment checks if the build succeeded
after_success:
  # Deployment steps (on success & on the correct branch)
  - bin/deploy
