##
# Personal site configurations
##

# Site-wide global settings
title: Jason Yao
description: > # this means to ignore newlines until "baseurl:"
  Canadian-born, Hong Kong raised, NYC situated developer.
  I like to make and break things, and can do everything
  from singing badly in the showers to building out
  large-scale application features meant to reach millions.
  I also love running, gaming, and binging on Netflix
  and HBO shows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.JasonYao.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/

#google_analytics: TODO

# Social
github_username: JasonYao
linkedin_username: JasonYaoNYU
email_username: Hello
phone_number: +1 (949) 335-2639

exclude:
  - Gemfile
  - Gemfile.lock
  - PSDs/