##
# Personal site configurations
##

# Site-wide global settings
title: Jason Yao
description: > # this means to ignore newlines until "baseurl:"
  My personal website for technical articles, memes,
  and rants. None of this nor I should be taken seriously
  at any point in time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.JasonYao.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/

gems:
  - jekyll-sitemap

# Social
github_username: JasonYao
linkedin_username: JasonYaoNYU
email_username: Hello
phone_number: +1 (949) 335-2639

# Analytics
google_analytics: true

# Collections
collections:
  projects:
    permalink: /projects/:path/
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - PSDs/
  - assets/ajax/*.html
  - assets/plugins/*.html
